name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 128.199.202.18
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Activate Node.js 18.18.2 using nvm or n (assuming you have nvm or n installed on your remote server)
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
            nvm use 18.18.2
            node -v
            cd /var/www/production/elite-portfolio
            git pull origin main
            npm install
            npm run build

      - name: Copy build files to server
        uses: appleboy/scp-action@master
        with:
          host: 128.199.202.18
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/*" # Source files or directories
          target: "/var/www/production/elite-portfolio" # Destination directory on server
